# Netlify配置
[build]
  command = "npm install && npx hexo clean && npx hexo generate --config _config.yml,_config.production.yml"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  # 确保使用生产环境配置
  NODE_ENV = "production"
  HEXO_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.{jpg,jpeg,png,gif,svg,webp,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
